/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdActivityRouteImport } from './routes/$projectId.activity'
import { Route as ProjectIdDashboardRouteImport } from './routes/$projectId.dashboard'
import { Route as ProjectIdSearchRouteImport } from './routes/$projectId.search'
import { Route as ProjectIdSettingsRouteImport } from './routes/$projectId.settings'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiPortabilityRouteImport } from './routes/api/portability'
import { Route as ProjectIdTasksIndexRouteImport } from './routes/$projectId.tasks.index'
import { Route as ProjectIdTasksTaskIdRouteImport } from './routes/$projectId.tasks.$taskId'
import { Route as ProjectIdViewsViewIdRouteImport } from './routes/$projectId.views.$viewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdActivityRoute = ProjectIdActivityRouteImport.update({
  id: '/$projectId/activity',
  path: '/$projectId/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdDashboardRoute = ProjectIdDashboardRouteImport.update({
  id: '/$projectId/dashboard',
  path: '/$projectId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSearchRoute = ProjectIdSearchRouteImport.update({
  id: '/$projectId/search',
  path: '/$projectId/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSettingsRoute = ProjectIdSettingsRouteImport.update({
  id: '/$projectId/settings',
  path: '/$projectId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortabilityRoute = ApiPortabilityRouteImport.update({
  id: '/api/portability',
  path: '/api/portability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdTasksIndexRoute = ProjectIdTasksIndexRouteImport.update({
  id: '/$projectId/tasks/',
  path: '/$projectId/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdTasksTaskIdRoute = ProjectIdTasksTaskIdRouteImport.update({
  id: '/$projectId/tasks/$taskId',
  path: '/$projectId/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdViewsViewIdRoute = ProjectIdViewsViewIdRouteImport.update({
  id: '/$projectId/views/$viewId',
  path: '/$projectId/views/$viewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId/activity': typeof ProjectIdActivityRoute
  '/$projectId/dashboard': typeof ProjectIdDashboardRoute
  '/$projectId/search': typeof ProjectIdSearchRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/portability': typeof ApiPortabilityRoute
  '/$projectId/tasks/$taskId': typeof ProjectIdTasksTaskIdRoute
  '/$projectId/views/$viewId': typeof ProjectIdViewsViewIdRoute
  '/$projectId/tasks/': typeof ProjectIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId/activity': typeof ProjectIdActivityRoute
  '/$projectId/dashboard': typeof ProjectIdDashboardRoute
  '/$projectId/search': typeof ProjectIdSearchRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/portability': typeof ApiPortabilityRoute
  '/$projectId/tasks/$taskId': typeof ProjectIdTasksTaskIdRoute
  '/$projectId/views/$viewId': typeof ProjectIdViewsViewIdRoute
  '/$projectId/tasks': typeof ProjectIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId/activity': typeof ProjectIdActivityRoute
  '/$projectId/dashboard': typeof ProjectIdDashboardRoute
  '/$projectId/search': typeof ProjectIdSearchRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/portability': typeof ApiPortabilityRoute
  '/$projectId/tasks/$taskId': typeof ProjectIdTasksTaskIdRoute
  '/$projectId/views/$viewId': typeof ProjectIdViewsViewIdRoute
  '/$projectId/tasks/': typeof ProjectIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId/activity'
    | '/$projectId/dashboard'
    | '/$projectId/search'
    | '/$projectId/settings'
    | '/api/events'
    | '/api/mcp'
    | '/api/portability'
    | '/$projectId/tasks/$taskId'
    | '/$projectId/views/$viewId'
    | '/$projectId/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectId/activity'
    | '/$projectId/dashboard'
    | '/$projectId/search'
    | '/$projectId/settings'
    | '/api/events'
    | '/api/mcp'
    | '/api/portability'
    | '/$projectId/tasks/$taskId'
    | '/$projectId/views/$viewId'
    | '/$projectId/tasks'
  id:
    | '__root__'
    | '/'
    | '/$projectId/activity'
    | '/$projectId/dashboard'
    | '/$projectId/search'
    | '/$projectId/settings'
    | '/api/events'
    | '/api/mcp'
    | '/api/portability'
    | '/$projectId/tasks/$taskId'
    | '/$projectId/views/$viewId'
    | '/$projectId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdActivityRoute: typeof ProjectIdActivityRoute
  ProjectIdDashboardRoute: typeof ProjectIdDashboardRoute
  ProjectIdSearchRoute: typeof ProjectIdSearchRoute
  ProjectIdSettingsRoute: typeof ProjectIdSettingsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPortabilityRoute: typeof ApiPortabilityRoute
  ProjectIdTasksTaskIdRoute: typeof ProjectIdTasksTaskIdRoute
  ProjectIdViewsViewIdRoute: typeof ProjectIdViewsViewIdRoute
  ProjectIdTasksIndexRoute: typeof ProjectIdTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/activity': {
      id: '/$projectId/activity'
      path: '/$projectId/activity'
      fullPath: '/$projectId/activity'
      preLoaderRoute: typeof ProjectIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/dashboard': {
      id: '/$projectId/dashboard'
      path: '/$projectId/dashboard'
      fullPath: '/$projectId/dashboard'
      preLoaderRoute: typeof ProjectIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/search': {
      id: '/$projectId/search'
      path: '/$projectId/search'
      fullPath: '/$projectId/search'
      preLoaderRoute: typeof ProjectIdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/settings': {
      id: '/$projectId/settings'
      path: '/$projectId/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portability': {
      id: '/api/portability'
      path: '/api/portability'
      fullPath: '/api/portability'
      preLoaderRoute: typeof ApiPortabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/tasks/': {
      id: '/$projectId/tasks/'
      path: '/$projectId/tasks'
      fullPath: '/$projectId/tasks/'
      preLoaderRoute: typeof ProjectIdTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/tasks/$taskId': {
      id: '/$projectId/tasks/$taskId'
      path: '/$projectId/tasks/$taskId'
      fullPath: '/$projectId/tasks/$taskId'
      preLoaderRoute: typeof ProjectIdTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/views/$viewId': {
      id: '/$projectId/views/$viewId'
      path: '/$projectId/views/$viewId'
      fullPath: '/$projectId/views/$viewId'
      preLoaderRoute: typeof ProjectIdViewsViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdActivityRoute: ProjectIdActivityRoute,
  ProjectIdDashboardRoute: ProjectIdDashboardRoute,
  ProjectIdSearchRoute: ProjectIdSearchRoute,
  ProjectIdSettingsRoute: ProjectIdSettingsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPortabilityRoute: ApiPortabilityRoute,
  ProjectIdTasksTaskIdRoute: ProjectIdTasksTaskIdRoute,
  ProjectIdViewsViewIdRoute: ProjectIdViewsViewIdRoute,
  ProjectIdTasksIndexRoute: ProjectIdTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
